name: Security Scans

on:
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Semgrep - Static Analysis
        uses: returntocorp/semgrep-action@v1
        with:
          config: ./sast/semgrep/rules

      - name: Trivy - Dependency and IaC Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH

      - name: Gitleaks - Secrets Detection
        uses: gitleaks/gitleaks-action@v2

      - name: Generate SBOM
        run: |
          curl -sSfL https://raw.githubusercontent.com/CycloneDX/cyclonedx-cli/main/install.sh | sh -s -- -b /usr/local/bin
          cyclonedx-app -i . -o sbom/cyclonedx.json